"""Add flagged to student

Revision ID: 6333efb296e0
Revises: 7168199119bb
Create Date: 2025-09-19 21:38:30.794539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6333efb296e0'
down_revision: Union[str, Sequence[str], None] = '7168199119bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('flagged', sa.Boolean(), nullable=True))
    op.add_column('attendance', sa.Column('morning_status', sa.String(length=10), nullable=False))
    op.add_column('attendance', sa.Column('afternoon_status', sa.String(length=10), nullable=False))
    op.add_column('attendance', sa.Column('morning_method', sa.String(length=10), nullable=False))
    op.add_column('attendance', sa.Column('afternoon_method', sa.String(length=10), nullable=False))
    op.alter_column('attendance', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.drop_column('attendance', 'status')
    op.add_column('students', sa.Column('flagged', sa.Boolean(), nullable=True))
    op.add_column('teachers', sa.Column('flagged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'flagged')
    op.drop_column('students', 'flagged')
    op.add_column('attendance', sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.alter_column('attendance', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('attendance', 'afternoon_method')
    op.drop_column('attendance', 'morning_method')
    op.drop_column('attendance', 'afternoon_status')
    op.drop_column('attendance', 'morning_status')
    op.drop_column('administrators', 'flagged')
    # ### end Alembic commands ###
