"""remove superadmin_id from administrators

Revision ID: 7168199119bb
Revises: 789c1da5e60b
Create Date: 2025-09-19 17:04:38.264702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7168199119bb'
down_revision: Union[str, Sequence[str], None] = '789c1da5e60b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('administrators_superadmin_id_fkey'), 'administrators', type_='foreignkey')
    op.drop_column('administrators', 'superadmin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('superadmin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('administrators_superadmin_id_fkey'), 'administrators', 'superadmins', ['superadmin_id'], ['id'])
    # ### end Alembic commands ###
